#!/bin/bash
# Build the Android App Bundle and publish it to a Google Play track.
#
#   bash scripts/publish-play.sh [track] [--no-build]
#
#   track       internal (default) | alpha | beta | production
#   --no-build  publish the bundle already in build/, without rebuilding
#
# Play rejects a bundle that is debug-signed, and rejects a versionCode that is
# not higher than what the track already has. Both are checked here, before the
# 46MB upload rather than after it, because Google's error arrives several
# minutes in and says less about how to fix it.
#
# Needs /root/secure/play-publisher.json — a Play Developer API service account
# key, NOT the Firebase one. See docs/play-console-publishing.md.
set -euo pipefail

TRACK="${1:-internal}"
BUILD=true
for a in "$@"; do [ "$a" = "--no-build" ] && BUILD=false; done
case "$TRACK" in internal|alpha|beta|production) ;; --no-build) TRACK=internal ;;
  *) echo "Unknown track: $TRACK (internal|alpha|beta|production)" >&2; exit 1 ;; esac

KEY=/root/secure/play-publisher.json
APP=/root/ugstream/mobile
AAB="$APP/build/app/outputs/bundle/release/app-release.aab"
PKG=com.prosystemsug.muzawatch

[ -f "$KEY" ] || { echo "Missing $KEY" >&2; exit 1; }

export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
export ANDROID_SDK_ROOT=/opt/android-sdk ANDROID_HOME=/opt/android-sdk
export PATH="$PATH:/opt/flutter/bin:/opt/android-sdk/platform-tools"

cd "$APP"
if $BUILD; then
  flutter pub get
  # android/ is regenerated by the build, so icons written into it by hand are
  # lost — generate them here as the APK script does.
  dart run flutter_launcher_icons
  flutter test
  flutter build appbundle --release --dart-define=API_BASE=https://ham.sentepos.com/api/v1 --dart-define=STORE=play
fi
[ -f "$AAB" ] || { echo "No bundle at $AAB" >&2; exit 1; }

# Refuse a debug-signed bundle. build.gradle.kts falls back to debug keys when
# the keystore is missing, which is right for a local build but would upload an
# artifact Play cannot accept — and, if it ever did, one that no properly
# signed build could update over.
JARSIGNER=$(find "$JAVA_HOME" -name jarsigner | head -1)
CERT=$("$JARSIGNER" -verify -verbose:summary -certs "$AAB" 2>/dev/null | grep -m1 'CN=' || true)
echo "signed by:${CERT:-  unknown}"
if [ -z "$CERT" ] || echo "$CERT" | grep -q 'CN=Android Debug'; then
  echo "refusing to publish: bundle is debug-signed or unsigned." >&2
  exit 1
fi

# The versionCode this build carries, from pubspec — the number after the "+".
# Read from there rather than from the bundle because an .aab stores its
# manifest as protobuf, and `aapt2 dump badging` only understands APKs: pointed
# at a bundle it returns nothing at all, so the check it was feeding silently
# never ran.
LOCAL_VERSION_CODE=$(grep -m1 '^version:' pubspec.yaml | sed -E 's/.*\+([0-9]+).*/\1/')
[ -n "$LOCAL_VERSION_CODE" ] && echo "bundle versionCode: $LOCAL_VERSION_CODE"

TRACK="$TRACK" KEY="$KEY" AAB="$AAB" PKG="$PKG" LOCAL_VERSION_CODE="${LOCAL_VERSION_CODE:-}" python3 - <<'PY'
import os, sys, requests
from google.oauth2 import service_account
import google.auth.transport.requests

KEY, AAB, PKG, TRACK = os.environ['KEY'], os.environ['AAB'], os.environ['PKG'], os.environ['TRACK']
creds = service_account.Credentials.from_service_account_file(
    KEY, scopes=['https://www.googleapis.com/auth/androidpublisher'])
creds.refresh(google.auth.transport.requests.Request())
h = {'Authorization': f'Bearer {creds.token}'}
base = f'https://androidpublisher.googleapis.com/androidpublisher/v3/applications/{PKG}'
up   = f'https://androidpublisher.googleapis.com/upload/androidpublisher/v3/applications/{PKG}'

eid = requests.post(f'{base}/edits', headers=h, timeout=60).json()['id']

def discard(msg):
    requests.delete(f'{base}/edits/{eid}', headers=h, timeout=30)
    print(msg, file=sys.stderr); sys.exit(1)

try:
    # What the track already has, so a duplicate versionCode is caught before
    # the upload rather than by Google afterwards.
    tracks = requests.get(f'{base}/edits/{eid}/tracks', headers=h, timeout=60).json()
    existing = [int(v) for t in tracks.get('tracks', []) if t['track'] == TRACK
                for r in (t.get('releases') or []) for v in (r.get('versionCodes') or [])]
    if existing:
        print(f'{TRACK} currently has versionCode {max(existing)}')

    # The bundle's own versionCode, read locally, so a duplicate is caught
    # before a 46MB upload rather than after it. Google refuses it either way;
    # this just fails in seconds instead of minutes.
    local_vc = int(os.environ.get('LOCAL_VERSION_CODE') or 0)
    if local_vc and existing and local_vc <= max(existing):
        discard(f'versionCode {local_vc} is not higher than {max(existing)} already '
                f'on {TRACK}. Raise it in mobile/pubspec.yaml (the number after "+").')

    size = os.path.getsize(AAB) / 1024 / 1024
    print(f'uploading {size:.1f} MB …')
    with open(AAB, 'rb') as f:
        r = requests.post(f'{up}/edits/{eid}/bundles?uploadType=media',
                          headers={**h, 'Content-Type': 'application/octet-stream'},
                          data=f, timeout=1800)
    if r.status_code != 200:
        discard(f'upload failed {r.status_code}: {r.text[:400]}')
    vc = int(r.json()['versionCode'])
    print('uploaded versionCode', vc)

    if existing and vc <= max(existing):
        discard(f'versionCode {vc} is not higher than {max(existing)} already on '
                f'{TRACK}. Raise it in mobile/pubspec.yaml (the number after "+").')

    notes = os.environ.get('RELEASE_NOTES', 'Fixes and improvements.')
    body = {'releases': [{'versionCodes': [str(vc)], 'status': 'completed',
                          'releaseNotes': [{'language': 'en-US', 'text': notes}]}]}
    t = requests.put(f'{base}/edits/{eid}/tracks/{TRACK}', headers=h, json=body, timeout=60)
    if t.status_code != 200:
        discard(f'track update failed {t.status_code}: {t.text[:400]}')

    c = requests.post(f'{base}/edits/{eid}:commit', headers=h, timeout=180)
    if c.status_code != 200:
        discard(f'commit failed {c.status_code}: {c.text[:400]}')
    print(f'published versionCode {vc} to {TRACK}')
except SystemExit:
    raise
except Exception as e:
    discard(f'aborted, edit discarded: {e}')
PY

echo
echo "Play Console → Testing → ${TRACK} should show it within a minute or two."
